version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ltail
    binary: ltail
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - id: ltail
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: ltail
    repository:
      owner: megaproaktiv
      name: homebrew-ltail
    commit_author:
      name: Megaproaktiv
      email: silberkopf@gmail.com
    directory: Formula
    homepage: "https://www.go-on-aws.com"
    description: "Based on TylerBrock/saw - Fast, multipurpose tool for AWS Lambda CloudWatch Logs"
    license: MIT

git:
  ignore_tags:
    - nightly
